### ISSUE TITLE
Testing with turtlebot3 environment 

### ISSUE THREAD

**Issue by Muhammad540** [babahadjsaid/elevation_mapping#2]
First of all, thank you for the great work in porting this to Humble. I was in the process of porting it myself when I found your repository. I am testing the elevation mapping using the TurtleBot3 environment. The TurtleBot3 publishes point cloud data and the robot pose on the /cloud/points and /robot_state/pose topics, respectively. I successfully built your package. After modifying the ground_truth_demo yaml, i was successfully able to provide the relevant topic to the elevation mapping node, but i am experiencing the following error, [elevation_mapping-1] [ERROR] [1719990711.628701039] [elevation_mapping]: Could not get pose information from robot for time 2613.695000. Buffer empty?  Here is the rqt graph: 
![image](https://github.com/babahadjsaid/elevation_mapping/assets/63818490/b1509f84-4cec-45dc-9553-305ed482f319)

**Comment by babahadjsaid** [comment]
Hello, so i think the problem is either the pose of the robot is not published, or there is a problem on the time of the pose being published, mybe the time is old. you need to check this in rqt /pose_publisher topic ( according to the rqt_graph you sent), also can you check weather the published pose is of type nav_msgs::msg::Odometry.

**Comment by Muhammad540** [comment]
Thank you so much for your prompt response. Your advice helped me resolve the buffer empty error. I checked the pose and timestamps, and they were correct. When I switched to publishing the robot pose using _nav_msgs/msg/Odometry_ instead of _geometry_msgs/PoseWithCovarianceStamped_, the error was resolved.

Now, although the mapping process seems to have started without errors, I still don't see any elevation map in RViz. The output of the _/elevation_map_ topic is showing NaN values. Here is the command line output after the elevation node starts:

![image](https://github.com/babahadjsaid/elevation_mapping/assets/63818490/ccfb9cc1-35e5-45f6-9116-c59aad251b38)

And here is the output of the /elevation_map topic:
![image](https://github.com/babahadjsaid/elevation_mapping/assets/63818490/c33ddc33-94f0-4f8e-aa8e-e62331fb7080)
It seems that the variance is too high, which might be causing the NaN values. Did you experience such an issue? Maybe we need to tweak some parameters. I would be really grateful if you could help me understand how to address this problem. Also i suspected maybe this a transform issue, here is the transform tree:  ![image](https://github.com/babahadjsaid/elevation_mapping/assets/63818490/9e1b5133-9263-4676-972e-50574457eca4). I am just speculating, maybe it is something else. Also this is the ground_truth_demo.yaml file 
![image](https://github.com/babahadjsaid/elevation_mapping/assets/63818490/b170d929-2a9f-4940-992e-0c88870fa35b)

**Comment by babahadjsaid** [comment]
I just saw your question, did you solve it or not yet ?

**Comment by Muhammad540** [comment]
Yes, i was able to publish the elevation map, and the reason for NaN values was high variance so i reduced it. However, the elevation mapping is very slow, the map updates take alot of time. It is hard to see it working in real time in current situation, did you face the same issue ? I am thinking of using some point cloud filtering approaches.

**Comment by babahadjsaid** [comment]
for me i ended up developing my own approach because the package didn't meet my requirments, so i didn't really use it much. :/
concerning your approach depending on the problem you are trying to solve.

**Comment by alitekes1** [comment]
Can you explain why didn't meet your requirements this repo, @babahadjsaid? I am deal with quadruped robots and i want to implement my navigation stack using the repo. I am researching that the most suitable mapping algorithm for legged robots. i encountered this repo and it looks like nice for quadrupeds. What are you thinking about this repo with pros and cons? @Muhammad540 I would like to hear your thoughts on the repo too. Do you think this repo is suitable for quadrupeds?

**Comment by Muhammad540** [comment]
> Can you explain why didn't meet your requirements this repo, @babahadjsaid? I am deal with quadruped robots and i want to implement my navigation stack using the repo. I am researching that the most suitable mapping algorithm for legged robots. i encountered this repo and it looks like nice for quadrupeds. What are you thinking about this repo with pros and cons? @Muhammad540 I would like to hear your thoughts on the repo too. Do you think this repo is suitable for quadrupeds?

Hey ali ! Thanks for reaching out. This repo is very good for elevation mapping and later on if you intend to use ETH zurich's Traversability implementation. This fits quite well. But from my experience it is very bloated, the same functionality can be easily implemented in a much shorter way. If your goal is to get traversability information about the environment to help your quadruped navigate then you can directly process pointcloud and compute traversability on the fly for that you may also read eth zurich's traversability paper. This repo is good to get you started and for quick demos but i wouldnt recommend to use it in production rather implement a simple smaller version, of course you may take inspiration from this.

**Comment by alitekes1** [comment]
thanks a lot your response. i will try to your [traversability repository](https://github.com/Muhammad540/traversability_estimation)
